### ISSUE TITLE
Detecting if a clip is from a Demo Match

### ISSUE THREAD

**Issue by SerialForBreakfast** [mdiller/twitchclipmatchfinder#3]
Take a look at running finder.py on this clip:
https://clips.twitch.tv/TransparentThankfulSparrowUncleNox
It throws an error and exits if there isn't an ID which really is probably fine because there isn't a match ID.  
I was wondering if I could have you add an npc_not_loaded option using an image like that?  https://i.imgur.com/EGMW9eX.png 
Can you add an npc_not_loaded directory with that image to:
http://dotabase.dillerm.io/dota-vpk/?dir=panorama/images/heroes
Then something like:
		#Detect if hero is not loaded before adding
		if hero.image != npc_not_loaded
			self.add_image(hero.image)
		else:
			print('No valid match to extract.  Possibly a Demo.')

**Comment by mdiller** [comment]
So this looks like a good way to deal with demo matches, but since this is just another case where we can't do anything more with the clip, I'd rather just leave it how it is, as the result is going to be the same: we cant associate a match with this clip. The reddit bot wouldn't use this and I don't see a use for this unless you were manually doing this yourself or something.

It would also require a decent amount of changes to the code to allow for finding things that aren't heroes or arcanas and finding multiple of a single thing in one image. I think for now I'll just leave it how it is, but its a good idea if you wanted to try implementing it yourself!
