### ISSUE TITLE
Accuracy of Template Matching

### ISSUE THREAD

**Issue by faizankshaikh** [mdiller/twitchclipmatchfinder#7]
Not an issue per se, just curious. 

How accurately are you able to find the appropriate hero based on a template image? Also, is there a chance this would require Deep Learning here (or anywhere in the project)?

**Comment by mdiller** [comment]
So if you look at the bottom of the README, it has some output with some numbers. the numbers on the right for each hero is how confident the image detection algorithm is that the hero image is in that position. The way i select which heroes though isnt to just grab the 10 most confident results, instead i go to each slot where i expect a hero, and look at all heros that the algorithm thinks exist at that slot. i then pick the most confident one out of those. I've found this works decently well. This also means that the only way it can really break is that if somehow the slot is in the wrong place, because its quite unlikely it will think the hero is somewhere else. I don't think deep learning would be very useful here, and you'd also probably have issues getting enough data to train it with.
